set nocompatible
syntax on
filetype plugin indent on
set autoindent
" set nowrap
set encoding=utf8
set clipboard^=unnamed,unnamedplus
set number
set cursorline
set colorcolumn=80
set mouse=a
set scrolloff=10
set autoread

let &t_SI = "\e[6 q"  " Set cursor to a vertical bar in insert mode
let &t_EI = "\e[2 q"  " Set cursor to a block in normal mode

" Make the escape key more responsive by decreasing the wait time for an
" escape sequence (e.g., arrow keys).
set ttimeout
set ttimeoutlen=50
set timeoutlen=500

" hlsearch
set hlsearch
set incsearch

set smarttab

set list
set listchars=tab:→\ ,trail:·,extends:…,precedes:…,nbsp:•
"listchars+=eol:¬,space:·

nnoremap ; :
set exrc " use local .vimrc files

"set hidden
set nohidden " this is the default value


" highlight colors
"hi MatchParen cterm=bold,underline ctermbg=gray ctermfg=red
"hi Search cterm=bold,underline ctermbg=gray ctermfg=red

" autopairs without a plugin
" inoremap " ""<left>
" inoremap ' ''<left>
"inoremap ( ()<left>
"inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O


" leader
nnoremap <space> <nop>
let mapleader = "\<space>"
let maplocalleader = "\<space>"
" quit
nnoremap <leader>q :q<CR>
tnoremap <leader>q <C-\><C-N>:q!<CR>
" quick help
nnoremap <leader>? :tab :h quickref<CR>
" terminal mode
" double tap esc to enter normal mode (inside terminal mode)
tnoremap <Esc><Esc> <C-\><C-N>
" open terminal in current window
"noremap <leader>t :ter ++curwin<CR>
" open terminal in new window
noremap <leader>t :new ter<CR>
" open terminal in new tab
noremap <leader>T :tab ter<CR>
" :ter to open new terminal in split window
" reload vim configuration
nnoremap <silent> <Leader>r :so $MYVIMRC<CR> :nohls<cr><left>
" clear search
nnoremap <silent> <leader>/ :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
" windows
nnoremap <leader>s :new<cr>
tnoremap <leader>s <C-\><C-N>:new<cr>
nnoremap <leader>v vnew<cr>
nnoremap <leader>v <C-\><C-N>vnew<cr>
nnoremap <leader>h <C-w>h
nnoremap <leader>j <C-w>j
nnoremap <leader>k <C-w>k
nnoremap <leader>l <C-w>l
tnoremap <leader>h <C-\><C-N><C-w>h
tnoremap <leader>j <C-\><C-N><C-w>j
tnoremap <leader>k <C-\><C-N><C-w>k
tnoremap <leader>l <C-\><C-N><C-w>l
" not a great idea to use leader in insert mode...
"inoremap <leader>h <C-\><C-N><C-w>h
"inoremap <leader>j <C-\><C-N><C-w>j
"inoremap <leader>k <C-\><C-N><C-w>k
"inoremap <leader>l <C-\><C-N><C-w>l
" tabs
" gt - go to next tab
" gT - go to previous tab
"noremap <leader>t :tabnew<CR>
nnoremap <leader>n gt
nnoremap <leader>p gT
" gf - go to file under the cursor
" <C-w>gf - go to file under the cursor in a new tab


" workaround to make system clipboard work in wayland
"https://github.com/vim/vim/issues/5157
if $XDG_SESSION_TYPE=='wayland'
	augroup wl-clipboard
	    autocmd!
	    autocmd FocusLost * :call system('wl-copy --trim-newline', @+)
	    autocmd FocusGained * :let @+ = system('wl-paste -n')
	augroup END
endif


runtime ftplugin/man.vim

call plug#begin()

Plug 'mhinz/vim-startify'
Plug 'chriskempson/base16-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
Plug 'preservim/tagbar'
Plug 'ludovicchabant/vim-gutentags'
Plug 'dense-analysis/ale'

Plug 'rhysd/vim-clang-format'

"Plug 'maralla/completor.vim'
"Plug 'ervandew/supertab'

call plug#end()

"let g:deoplete#enable_at_startup = 1

"let g:ale_c_parse_makefile = 1
"let g:ale_linters = {'c': ['gcc']}

" airline
let g:airline_theme='monochrome'

" are we in tty?
"if $TERM != 'linux' " this will fail when running tmux from tty
if !empty($DISPLAY)
	let g:airline_powerline_fonts = 1
	let base16colorspace=256
	set termguicolors
	let g:airline_theme='base16'
endif


" tagbar
nmap <F5> :TagbarToggle<CR>

"ale
set path=.,/usr/include,/usr/include/x86_64-linux-gnu,,
let g:ale_linters = {'c': ['gcc']}
let g:ale_c_cc_executable = 'gcc'
"let g:ale_c_cc_options = '-std=c11 -Wall'
let g:ale_c_cc_options = '-std=gnu11 -Wall'


"colorscheme - run after loading base16 plugin
colorscheme base16-default-dark
"colorscheme default

"nerdtree
nnoremap <C-t> :NERDTreeToggle<CR>

"startify
let g:startify_custom_header = readfile($"{getenv('HOME')}/.config/vim/startify-message.txt")

