-- autogenerated
vim.g.have_nerd_font = true
vim.opt.number = true
vim.opt.mouse = 'a'

--[[
**** amsp begin ****
]]

-- colorscheme of choice
vim.cmd 'colorscheme slate'

-- use system clipboard
vim.opt.clipboard = 'unnamedplus'

-- ';' is easier to type than ':'
vim.api.nvim_set_keymap("", ";", ":", {noremap = true})

-- hidden characters
vim.opt.list = true
vim.opt.listchars:append {
	tab = "→ ",
	trail = "·",
	extends = "…",
	precedes = "…",
	nbsp = "•",
}

-- autopairs
vim.api.nvim_set_keymap("i", '"', '""<left>', {noremap = true})
vim.api.nvim_set_keymap("i", "'", "''<left>", {noremap = true})
vim.api.nvim_set_keymap("i", "(", "()<left>", {noremap = true})
vim.api.nvim_set_keymap("i", "[", "[]<left>", {noremap = true})
vim.api.nvim_set_keymap("i", "{", "{}<left>", {noremap = true})
vim.api.nvim_set_keymap("i", "{<CR>", "{<CR>}<ESC>O", {noremap = true})
vim.api.nvim_set_keymap("i", "{;<CR>", "{<CR>};<ESC>O", {noremap = true})

--[[
**** amsp end ****
]]
